# Generated by Django 4.0.5 on 2022-06-23 15:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_qty', models.IntegerField(blank=True, null=True, verbose_name='Количество игроков')),
                ('players_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя игрока')),
                ('rounds_qty', models.PositiveIntegerField(default=0, verbose_name='Количество сыгранных раундов')),
                ('average_spin', models.PositiveIntegerField(default=0, verbose_name='Среднее количество вращений')),
                ('game', models.ManyToManyField(to='roulette_app.game', verbose_name='Участвовал в играх')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='players', to='roulette_app.player', verbose_name='Участвовавшие игроки'),
        ),
    ]
