# Generated by Django 4.0.5 on 2022-06-23 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(null=True, related_name='players', to='roulette_app.player', verbose_name='Участвовавшие игроки'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
