# Generated by Django 4.0.5 on 2022-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0003_alter_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ManyToManyField(null=True, to='roulette_app.game', verbose_name='Участвовал в играх'),
        ),
    ]
