# Generated by Django 4.0.5 on 2022-06-23 15:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0004_alter_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], null=True, size=None),
        ),
    ]
