# Generated by Django 4.0.5 on 2022-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0005_alter_game_players_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='players', to='roulette_app.player', verbose_name='Участвовавшие игроки'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ManyToManyField(to='roulette_app.game', verbose_name='Участвовал в играх'),
        ),
    ]
