# Generated by Django 4.0.5 on 2022-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0006_alter_game_players_alter_player_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='spins',
            field=models.IntegerField(default=0, verbose_name='Всего сделано прокручиваний рулетки'),
        ),
    ]
