# Generated by Django 4.0.5 on 2022-06-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0007_player_spins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
    ]
